// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc6597.CompBot.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc6597.CompBot.Robot;

/**
 *
 */
public class ArmCmd extends Command {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public ArmCmd() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.armSub);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
       if(Robot.oi.copController.getRawButton(1)){
           Robot.armSub.desiredposition=Robot.armSub.POSITION_BALL;
       }
       if(Robot.oi.copController.getRawButton(2)){
        Robot.armSub.desiredposition=Robot.armSub.POSITION_C1;
    }
    if(Robot.oi.copController.getRawButton(3)){
        Robot.armSub.desiredposition=Robot.armSub.POSITION_HATCH;
    }
    if(Robot.oi.copController.getRawButton(6)){
        Robot.armSub.desiredposition=Robot.armSub.POSITION_R2;
    }
    if(Robot.oi.copController.getRawButton(4)){
        Robot.armSub.desiredposition=Robot.armSub.POSITION_R1;
    }
       
       
        Robot.armSub.move();
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
        Robot.armSub.stop();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
    }
}
